services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "1.21.4"
      ONLINE_MODE: "FALSE"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./server-data:/data
